"""Initial migration

Revision ID: 7480b43ff43a
Revises: 
Create Date: 2024-10-29 00:05:00.369807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7480b43ff43a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=False),
    sa.Column('result_pos', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_pos')
    )
    op.create_index(op.f('ix_tests_fen'), 'tests', ['fen'], unique=True)
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_fen'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###
